### PR TITLE
Language updates

### PR DESCRIPTION
**Pull request by chrzyki**
With much help by @natalia-morozova.

### CODE REVIEW

**Comment by LinguList** [comment]
looks good, however, @chrzyki, I'd expect more changes in parameters.csv, as I corrected mappings in sun, could you maybe check that again, that you downloaded my pr from yesterday?

**Comment by chrzyki** [comment]
Thanks! They're probably missing because I'm building against Concepticon 2.0. Should I build against the most recent master?

**Comment by LinguList** [comment]
No, I find this okay, but I'd suggest to not release it, as for the official clics3, we'd have concepticon-2.1 as the better option, I think, or what do the others say?

**Comment by chrzyki** [comment]
Sounds reasonable to me!

**Pull request merged**
