### PR TITLE
Prepare release

### PR DESCRIPTION
**Pull request by chrzyki**
Should #9 be attempted as well before the release?

### CODE REVIEW

**Comment by FredericBlum** [comment]
I think we should try, yes. If I see this correctly, there is always tone defined after the vowels; also after /v/. So the easiest option would probably be to add things like [v1] and [v33] as vowels with the corresponding tone afterwards. And then watch carefully that this changes only the correct cases.

**Review by FredericBlum — COMMENTED** [review]
see comment about /v/

**Comment by FredericBlum** [comment]
@chrzyki I have added a fix that changes all occurrences of v before tones to the indicated vowel symbol (#9 )

**Comment by chrzyki** [comment]
Thanks, so this closes #9 .

**Pull request merged**
